[package]
name = "mhycrypt"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "mhycrypt"
crate-type = ["cdylib", "rlib"]

[dependencies]
rand_mt = "4.0.0"
